export const existsSync = () => false;
export const mkdirSync = () => {};
export const readFileSync = () => '';
export const writeFileSync = () => {};
export const readdirSync = () => [];
export const statSync = () => ({ isDirectory: () => false, isFile: () => true, mtime: new Date(), mode: 0o644 });
export const unlinkSync = () => {};
export const rmdirSync = () => {};
export const renameSync = () => {};
export const openSync = () => 0;
export const closeSync = () => {};
export const readSync = () => 0;
export const writeSync = () => 0;
export const fstatSync = () => ({ size: 0 });
export const realpathSync = () => '/';
export const lstatSync = () => ({ isDirectory: () => false, isFile: () => true, mode: 0o644, mtime: new Date(), size: 0 });
export const chmodSync = () => {};
export const utimesSync = () => {};
export const truncateSync = () => {};
export const ftruncateSync = () => {};
export const readFile = () => Promise.resolve('');
export const writeFile = () => Promise.resolve();
export const readdir = () => Promise.resolve([]);
export const stat = () => Promise.resolve({ isDirectory: () => false, isFile: () => true });
export const access = () => Promise.resolve();
export const mkdir = () => Promise.resolve();
export const constants = { O_RDONLY: 0, O_WRONLY: 1, O_RDWR: 2, O_CREAT: 64, O_EXCL: 128, O_TRUNC: 512, O_APPEND: 1024 };
export const promises = { readFile: () => Promise.resolve(''), writeFile: () => Promise.resolve() };
export const createReadStream = () => ({ on: () => {} });
export const createWriteStream = () => ({ on: () => {}, end: () => {} });

export const resolve = (...args: string[]) => args.filter(Boolean).join('/') || '/';
export const join = (...args: string[]) => args.filter(Boolean).join('/');
export const dirname = (p: string) => { const i = p.lastIndexOf('/'); return i > 0 ? p.slice(0, i) : '.'; };
export const basename = (p: string) => { const i = p.lastIndexOf('/'); return i >= 0 ? p.slice(i + 1) : p; };
export const extname = (p: string) => { const i = p.lastIndexOf('.'); return i > 0 ? p.slice(i) : ''; };
export const normalize = (p: string) => p;
export const relative = (_from: string, to: string) => to;
export const isAbsolute = (p: string) => p.startsWith('/');
export const sep = '/';
export const delimiter = ':';

export default { resolve, join, dirname, basename, extname, normalize, relative, isAbsolute, sep, delimiter };